services:
  db:
    image: postgis/postgis
    container_name: kora-postgis
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgis_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: kora_backend
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "${APP_PORT}:8000"
    volumes:
      - ./backend/src:/code/src:z
      - ./backend/Cargo.toml:/code/Cargo.toml
      - ./backend/Cargo.lock:/code/Cargo.lock
    command: cargo run --release

volumes:
  postgis_data:
    external: true
