[mypy]
plugins = mypy_django_plugin.main

mypy_path = src

# Nivel de estrictitud
strict = True

explicit_package_bases = True

# Opcionales útiles
ignore_missing_imports = False

[mypy.plugins.django-stubs]
django_settings_module = infrastructure.django.config.settings

[mypy-infrastructure.django.apps.*.models]
ignore_errors = True